"""add_indexes_and_dashboard_cache

Revision ID: 099d48fab4c9
Revises: cb49155e7cf3
Create Date: 2026-07-07 10:05:05.868266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '099d48fab4c9'
down_revision: Union[str, Sequence[str], None] = 'cb49155e7cf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_caches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=255), nullable=False),
    sa.Column('cached_data', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_caches_cache_key'), 'dashboard_caches', ['cache_key'], unique=True)
    op.create_index(op.f('ix_dashboard_caches_id'), 'dashboard_caches', ['id'], unique=False)
    op.create_index(op.f('ix_approval_tasks_employee_id'), 'approval_tasks', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_date'), 'attendance', ['date'], unique=False)
    op.create_index(op.f('ix_attendance_employee_id'), 'attendance', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_regularization_requests_attendance_date'), 'attendance_regularization_requests', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_attendance_regularization_requests_employee_id'), 'attendance_regularization_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employees_status'), 'employees', ['status'], unique=False)
    op.create_index(op.f('ix_login_activities_employee_id'), 'login_activities', ['employee_id'], unique=False)
    op.create_index(op.f('ix_login_activities_login_time'), 'login_activities', ['login_time'], unique=False)
    op.create_index(op.f('ix_login_activities_user_id'), 'login_activities', ['user_id'], unique=False)
    op.create_index(op.f('ix_timeoff_requests_date'), 'timeoff_requests', ['date'], unique=False)
    op.create_index(op.f('ix_timeoff_requests_employee_id'), 'timeoff_requests', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeoff_requests_employee_id'), table_name='timeoff_requests')
    op.drop_index(op.f('ix_timeoff_requests_date'), table_name='timeoff_requests')
    op.drop_index(op.f('ix_login_activities_user_id'), table_name='login_activities')
    op.drop_index(op.f('ix_login_activities_login_time'), table_name='login_activities')
    op.drop_index(op.f('ix_login_activities_employee_id'), table_name='login_activities')
    op.drop_index(op.f('ix_employees_status'), table_name='employees')
    op.drop_index(op.f('ix_attendance_regularization_requests_employee_id'), table_name='attendance_regularization_requests')
    op.drop_index(op.f('ix_attendance_regularization_requests_attendance_date'), table_name='attendance_regularization_requests')
    op.drop_index(op.f('ix_attendance_employee_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_date'), table_name='attendance')
    op.drop_index(op.f('ix_approval_tasks_employee_id'), table_name='approval_tasks')
    op.drop_index(op.f('ix_dashboard_caches_id'), table_name='dashboard_caches')
    op.drop_index(op.f('ix_dashboard_caches_cache_key'), table_name='dashboard_caches')
    op.drop_table('dashboard_caches')
    # ### end Alembic commands ###
