"""add_shift_break_policy_employee_shift_overtime_request

Revision ID: cb49155e7cf3
Revises: e950f75555ac
Create Date: 2026-07-01 13:30:33.401396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb49155e7cf3'
down_revision: Union[str, Sequence[str], None] = 'e950f75555ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('required_minutes', sa.Integer(), nullable=True),
    sa.Column('minimum_half_day_minutes', sa.Integer(), nullable=True),
    sa.Column('grace_minutes', sa.Integer(), nullable=True),
    sa.Column('late_arrival_policy', sa.String(length=255), nullable=True),
    sa.Column('early_exit_policy', sa.String(length=255), nullable=True),
    sa.Column('overtime_policy', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_attendance_policies_id'), 'attendance_policies', ['id'], unique=False)
    op.create_table('break_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('paid_break', sa.Boolean(), nullable=True),
    sa.Column('mandatory', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_break_policies_id'), 'break_policies', ['id'], unique=False)
    op.create_table('employee_shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_shifts_id'), 'employee_shifts', ['id'], unique=False)
    op.create_table('overtime_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('attendance_id', sa.Integer(), nullable=True),
    sa.Column('requested_minutes', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_overtime_requests_id'), 'overtime_requests', ['id'], unique=False)
    op.add_column('attendance_regularization_requests', sa.Column('auto_checkout_time', sa.Time(), nullable=True))
    op.add_column('attendance_regularization_requests', sa.Column('requested_time', sa.Time(), nullable=True))
    op.add_column('attendance_regularization_requests', sa.Column('corrected_time', sa.Time(), nullable=True))
    op.add_column('attendance_regularization_requests', sa.Column('manager_decision', sa.String(length=20), nullable=True))
    op.add_column('attendance_regularization_requests', sa.Column('hr_decision', sa.String(length=20), nullable=True))
    op.add_column('attendance_regularization_requests', sa.Column('audit_status', sa.String(length=20), nullable=True))
    op.add_column('shifts', sa.Column('start_time', sa.Time(), nullable=True))
    op.add_column('shifts', sa.Column('end_time', sa.Time(), nullable=True))
    op.add_column('shifts', sa.Column('required_work_minutes', sa.Integer(), nullable=True))
    op.add_column('shifts', sa.Column('grace_minutes', sa.Integer(), nullable=True))
    op.add_column('shifts', sa.Column('minimum_half_day_minutes', sa.Integer(), nullable=True))
    op.add_column('shifts', sa.Column('overtime_allowed', sa.Boolean(), nullable=True))
    op.add_column('shifts', sa.Column('max_overtime_minutes', sa.Integer(), nullable=True))
    op.add_column('shifts', sa.Column('timezone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shifts', 'timezone')
    op.drop_column('shifts', 'max_overtime_minutes')
    op.drop_column('shifts', 'overtime_allowed')
    op.drop_column('shifts', 'minimum_half_day_minutes')
    op.drop_column('shifts', 'grace_minutes')
    op.drop_column('shifts', 'required_work_minutes')
    op.drop_column('shifts', 'end_time')
    op.drop_column('shifts', 'start_time')
    op.drop_column('attendance_regularization_requests', 'audit_status')
    op.drop_column('attendance_regularization_requests', 'hr_decision')
    op.drop_column('attendance_regularization_requests', 'manager_decision')
    op.drop_column('attendance_regularization_requests', 'corrected_time')
    op.drop_column('attendance_regularization_requests', 'requested_time')
    op.drop_column('attendance_regularization_requests', 'auto_checkout_time')
    op.drop_index(op.f('ix_overtime_requests_id'), table_name='overtime_requests')
    op.drop_table('overtime_requests')
    op.drop_index(op.f('ix_employee_shifts_id'), table_name='employee_shifts')
    op.drop_table('employee_shifts')
    op.drop_index(op.f('ix_break_policies_id'), table_name='break_policies')
    op.drop_table('break_policies')
    op.drop_index(op.f('ix_attendance_policies_id'), table_name='attendance_policies')
    op.drop_table('attendance_policies')
    # ### end Alembic commands ###
